spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: user
    password: password
    platform: mysql
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialize: true
spring:
  profiles: development
  jpa:
    database: MYSQL
    properties:
      hibernate:
        default-schema: schema
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://mysql:3306/demo
    platform: mysql
    username: user
    password: password
    initialization-mode: always
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: test-service
server:
  port: 8198
