spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:demo}
    username: ${DATABASE_USER:user}
    password: ${DATABASE_PASSWORD:password}
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

---
spring:
  profiles: container
  datasource:
    initialize: true
spring:
  profiles: development
  jpa:
    database: MYSQL
    properties:
      hibernate:
        default-schema: schema
    hibernate:
      ddl-auto: create-drop
  datasource:
    initialization-mode: always
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: test-service
server:
  port: 8198
